/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Answer {
  answerer_id: string;
  choice: string;
  created_at: Generated<string>;
  question_id: string;
}

export interface Question {
  choice1: string;
  choice2: string;
  choice3: string;
  choice4: string;
  created_at: Generated<string>;
  id: string;
  text: string;
}

export interface Uptime {
  created_at: Generated<string>;
  id: string;
  time: Generated<number>;
}

export interface DB {
  answer: Answer;
  question: Question;
  uptime: Uptime;
}
